config:
  int: 1
  string: a
  intlist: [1,2,3]
  stringlist: [a,b,c]
  map:
    name: stuart
    age: 30
  listmap:
    -
      a: 1
      b: 2
    -
      x: 11
      y: 12
  maplist:
    ml1:
      -
        a: 1
        b: 2
      -
        x: 11
        y:  12
    ml2:
      - a: 1
        b: 2
      - x: 11
        y:  12